<a href="https://colab.research.google.com/github/ombhope/ma22c030_2023_pl/blob/main/Assignment%204/MA22C030PLA4_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import math

In [2]:
A = [0.1, 1.3, 0.4, 0.5] # list
a = np.array(A) # numpy array
type(a), type(A)

(numpy.ndarray, list)

In [3]:
a.dtype # a's common element type (A.dtype is undefined!)

dtype('float64')

In [4]:
2*a

array([0.2, 2.6, 0.8, 1. ])

In [5]:
2*A

[0.1, 1.3, 0.4, 0.5, 0.1, 1.3, 0.4, 0.5]

In [6]:
n = 100000
x = np.linspace(0, 2*np.pi, n)

In [7]:
# list comprehension
%timeit y = [math.sin(x[i]) * math.exp(-x[i]) for i in range(n)]
# use numpy ufuncs
%timeit y = np.sin(x) * np.exp(-x)

79.6 ms ± 25.8 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
2.62 ms ± 99.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [8]:
def f(v): # apply f to one scalar value v
  return math.sin(v) * math.exp(-v)

In [9]:
vectorizedf = map(f, x) # apply same f to a vector of values x

In [10]:
F = np.vectorize(f) # F can be applied to a array x

In [11]:
# use map
%timeit y = list(map(f, x))
# use numpy's vectorize
%timeit y = F(x)
# use numpy's ufunc
%timeit y = np.sin(x) * np.exp(-x)

38.8 ms ± 1.01 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
38.8 ms ± 1.46 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
3.47 ms ± 1.07 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [12]:
%timeit for x in range(1000000): x**3
%timeit for x in np.arange(1000000): x**3

527 ms ± 120 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
150 ms ± 46.1 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [13]:
a = np.random.randint(0,9,5)
a

array([7, 7, 2, 0, 8])

In [14]:
a[::]

array([7, 7, 2, 0, 8])

In [15]:
a[-3:]

array([2, 0, 8])

In [16]:
a[-1], a[len(a)-1]

(8, 8)

In [17]:
a[-4:-1:2]

array([7, 0])

In [18]:
slice = range(-4,-1,2) # Think of b:e:s specification as a range.
a[-4:-1:2], a[slice] # In older versions, a[slice] may not work
# but will work with slice=arange(-4,-1,2)

(array([7, 0]), array([7, 0]))

In [19]:
a = np.array([1,2,3])
b = np.array([3,4,5,6])

In [20]:
a = b
a[0] = 1
a

array([1, 4, 5, 6])

In [21]:
b

array([1, 4, 5, 6])

In [22]:
a = np.array([1,2,3]) # This is Object1 and "a" is a name for it.
b = np.array([3,4,5,6]) # This is Object2 and "b" is a name for it.

In [23]:
id(a), id(b)

(134155226881200, 134155226880624)

In [24]:
a = b # a is no longer a name for Object1, it is now a name for Object2.

In [25]:
id(a), id(b)

(134155226880624, 134155226880624)

In [26]:
a = np.array([1,2,3]) # Object1
b = np.array([3,4,5,6]) # Object2
a = b.copy() # Copies Object2, and binds a to the copy
a[0] = 2 # Only the copied (new) object is changed

In [27]:
a, b

(array([2, 4, 5, 6]), array([3, 4, 5, 6]))

In [28]:
Amat = [[1,2],
        [3,4]]
Amat

[[1, 2], [3, 4]]

In [29]:
amat = np.array(Amat)
amat

array([[1, 2],
       [3, 4]])

In [30]:
type(A), type(a)

(list, numpy.ndarray)

In [31]:
2*Amat

[[1, 2], [3, 4], [1, 2], [3, 4]]

In [32]:
2*amat

array([[2, 4],
       [6, 8]])

In [33]:
amat * amat

array([[ 1,  4],
       [ 9, 16]])

In [34]:
import sys
print(sys.version) # check if you have version >= 3.5 before trying @

3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]


In [35]:
amat @ amat

array([[ 7, 10],
       [15, 22]])

In [36]:
np.dot(amat, amat) # dot(A,B) = matrix A multiplied by matrix B

array([[ 7, 10],
       [15, 22]])

In [37]:
amat.dot(amat)

array([[ 7, 10],
       [15, 22]])

In [38]:
amat**2 # not equal to matrix power !!

array([[ 1,  4],
       [ 9, 16]])

In [39]:
np.linalg.matrix_power(amat, 2)

array([[ 7, 10],
       [15, 22]])

In [40]:
A = np.array([[7, 8, 5, 1], [2, 5, 5, 2], [9, 6, 8, 9]])
A

array([[7, 8, 5, 1],
       [2, 5, 5, 2],
       [9, 6, 8, 9]])

In [41]:
A[1, :], A[:, 2]

(array([2, 5, 5, 2]), array([5, 5, 8]))

In [42]:
A[:3:2, :3]

array([[7, 8, 5],
       [9, 6, 8]])

In [43]:
M = np.array([[7, 8, 5, 1], [2, 5, 5, 2], [9, 6, 8, 9]])
M

array([[7, 8, 5, 1],
       [2, 5, 5, 2],
       [9, 6, 8, 9]])

In [44]:
M.reshape(2, 6) # Just a different view of the same data

array([[7, 8, 5, 1, 2, 5],
       [5, 2, 9, 6, 8, 9]])

In [45]:
M.ravel() # The 1D data of M in row-major ordering

array([7, 8, 5, 1, 2, 5, 5, 2, 9, 6, 8, 9])

In [46]:
A = np.array(M, order='F')
A

array([[7, 8, 5, 1],
       [2, 5, 5, 2],
       [9, 6, 8, 9]])

In [47]:
A.ravel(order='A') # A's internal ordering is Fortran style

array([7, 2, 9, 8, 5, 6, 5, 5, 8, 1, 2, 9])

In [48]:
N = np.arange(25).reshape(5,5)
N

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [49]:
mask = (N>7) & (N<18)
mask

array([[False, False, False, False, False],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True, False, False],
       [False, False, False, False, False]])

In [50]:
N[mask]

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [51]:
i, j = np.where(mask) # Returns i and j indices where mask[i,j] is True.
i, j # 1st True value of mask is at i[0],j[0],
# 2nd True value of mask is at i[1],j[1], etc.

(array([1, 1, 2, 2, 2, 2, 2, 3, 3, 3]), array([3, 4, 0, 1, 2, 3, 4, 0, 1, 2]))

In [52]:
data = np.random.randint(low=0, high=10, size=30) # 1D array

In [53]:
T2 = np.reshape(data, (6, 5)) # 2D array
T2

array([[3, 8, 1, 6, 5],
       [5, 2, 3, 5, 5],
       [9, 2, 7, 1, 8],
       [2, 6, 0, 1, 3],
       [6, 6, 1, 6, 4],
       [8, 7, 0, 8, 9]])

In [54]:
T3 = np.reshape(data, (2, 3, 5)) # 3D array
T3

array([[[3, 8, 1, 6, 5],
        [5, 2, 3, 5, 5],
        [9, 2, 7, 1, 8]],

       [[2, 6, 0, 1, 3],
        [6, 6, 1, 6, 4],
        [8, 7, 0, 8, 9]]])

In [55]:
print('T3 is a ', T3.ndim, 'dimensional array of shape ', T3.shape)
print('T2 is a ', T2.ndim, 'dimensional array of shape ', T2.shape)
print('data is a ', data.ndim, 'dimensional array of shape ', data.shape)

T3 is a  3 dimensional array of shape  (2, 3, 5)
T2 is a  2 dimensional array of shape  (6, 5)
data is a  1 dimensional array of shape  (30,)
