<a href="https://colab.research.google.com/github/ombhope/ma22c030_2023_pl/blob/main/Assignment%205/MA22C030PLA5(Row_Swap).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import numpy as np


In [33]:
def SR(i, j, A):
    tmp = A[i, :]  # Make a copy of A[i,:] to avoid changing it
    A[i, :] = A[j, :]
    A[j, :] = tmp
    return A

In [34]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [35]:
A= SR(1, 2, A)
print(A)

[[1 2 3]
 [7 8 9]
 [7 8 9]]


In [36]:
# Using the SR_1 function
def SR_1(i, j, A):
    A[[i, j]] = A[[j, i]]
    return A

In [37]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [38]:
A = SR_1(1, 2, A)
print(A)

[[1 2 3]
 [7 8 9]
 [4 5 6]]
