<a href="https://colab.research.google.com/github/ombhope/ma22c030_2023_pl/blob/main/Assignment%208/MA22C030PLA8(Column_Space).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from scipy.linalg import svd, qr

In [2]:
# Create a random matrix A
A = np.array([[1, -2, 3, -3], [2, -4, 9, -2], [-3, 6, -9, 9]])

In [3]:
# Task 1: Singular Value Decomposition (SVD)
U_svd, S_svd, VT_svd = svd(A)

print("SVD U:")
print(U_svd)
print("SVD U Transpose:")
print(U_svd.T)

for i in range(3):
    basis_svd = U_svd.T[i]
    print("Basis SVD", i + 1, ":", basis_svd, end="  ")

SVD U:
[[ 2.66235859e-01  1.70641342e-01  9.48683298e-01]
 [ 5.39615303e-01 -8.41911709e-01 -5.55111512e-17]
 [-7.98707576e-01 -5.11924025e-01  3.16227766e-01]]
SVD U Transpose:
[[ 2.66235859e-01  5.39615303e-01 -7.98707576e-01]
 [ 1.70641342e-01 -8.41911709e-01 -5.11924025e-01]
 [ 9.48683298e-01 -5.55111512e-17  3.16227766e-01]]
Basis SVD 1 : [ 0.26623586  0.5396153  -0.79870758]  Basis SVD 2 : [ 0.17064134 -0.84191171 -0.51192403]  Basis SVD 3 : [ 9.48683298e-01 -5.55111512e-17  3.16227766e-01]  

In [4]:
# QR Decomposition
Q_qr, R_qr = qr(A)

print("\nQR Q:")
print(Q_qr)
print("QR R:")
print(R_qr)

for i in range(3):
    basis_qr = Q_qr.T[i]
    print("Basis QR", i + 1, ":", basis_qr, end="  ")


QR Q:
[[-0.26726124  0.95618289 -0.11952286]
 [-0.53452248 -0.04390192  0.84401323]
 [ 0.80178373  0.28945968  0.52283453]]
QR R:
[[-3.74165739e+00  7.48331477e+00 -1.28285396e+01  9.08688223e+00]
 [ 0.00000000e+00 -1.98602732e-15 -1.31705767e-01 -1.75607689e-01]
 [ 0.00000000e+00  0.00000000e+00  2.53203970e+00  3.37605293e+00]]
Basis QR 1 : [-0.26726124 -0.53452248  0.80178373]  Basis QR 2 : [ 0.95618289 -0.04390192  0.28945968]  Basis QR 3 : [-0.11952286  0.84401323  0.52283453]  

In [5]:
# Task 2: Verify if B1 and B2 span the same vector space
aug_uq = np.vstack((U_svd, Q_qr))  # Stack U_svd and Q_qr vertically
print("Augmented Matrix [U_svd, Q_qr]:")
print(aug_uq)

rank_aug_uq = np.linalg.matrix_rank(aug_uq)
print("Rank of [U_svd, Q_qr]:", rank_aug_uq)

Augmented Matrix [U_svd, Q_qr]:
[[ 2.66235859e-01  1.70641342e-01  9.48683298e-01]
 [ 5.39615303e-01 -8.41911709e-01 -5.55111512e-17]
 [-7.98707576e-01 -5.11924025e-01  3.16227766e-01]
 [-2.67261242e-01  9.56182887e-01 -1.19522861e-01]
 [-5.34522484e-01 -4.39019222e-02  8.44013232e-01]
 [ 8.01783726e-01  2.89459681e-01  5.22834534e-01]]
Rank of [U_svd, Q_qr]: 3


In [6]:
# Task 3: SVD and QR on a random matrix B
B = np.random.rand(500, 500)


In [7]:
# SVD
U_B, S_B, VT_B = svd(B)

In [8]:
# QR
Q_B, R_B = qr(B)


In [9]:
# Measure the execution time for SVD and QR
import timeit


In [10]:
print("Time taken for SVD:")
%timeit U_B, S_B, VT_B

Time taken for SVD:
47.7 ns ± 0.341 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [11]:
print("Time taken for QR:")
%timeit Q_B, R_B

Time taken for QR:
46.1 ns ± 13.2 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
