<a href="https://colab.research.google.com/github/ombhope/ma22c030_2023_pl/blob/main/Assignment%206/MA22C030PLA6(Pairwise_Differences).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
# Generate a 1D NumPy array 'data' of length 5 filled with random numbers between 0 and 1.
data = np.random.rand(5)
print("data =", data)

data = [0.11814511 0.59037772 0.03822136 0.01135431 0.20017033]


In [4]:
# Calculate the pairwise differences between elements of 'data' to create a 2D array 'diff_matrix'.
diff_matrix = np.subtract.outer(data, data)
print(diff_matrix)

[[ 0.         -0.4722326   0.07992375  0.1067908  -0.08202521]
 [ 0.4722326   0.          0.55215636  0.57902341  0.39020739]
 [-0.07992375 -0.55215636  0.          0.02686705 -0.16194896]
 [-0.1067908  -0.57902341 -0.02686705  0.         -0.18881601]
 [ 0.08202521 -0.39020739  0.16194896  0.18881601  0.        ]]


In [7]:

# Extended version using loops to calculate the differences and populate a 2D array 'result'.
result = np.zeros((5, 5))
for i in range(5):
    for j in range(5):
        result[i][j] = data[i] - data[j]

print(result)

[[ 0.         -0.4722326   0.07992375  0.1067908  -0.08202521]
 [ 0.4722326   0.          0.55215636  0.57902341  0.39020739]
 [-0.07992375 -0.55215636  0.          0.02686705 -0.16194896]
 [-0.1067908  -0.57902341 -0.02686705  0.         -0.18881601]
 [ 0.08202521 -0.39020739  0.16194896  0.18881601  0.        ]]
